name: urbanstay.com.au
favicon: null
layout_spectrum: 0.6334382647182792
typography_spectrum: 0.8402711900416762
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.44853062159381807
  lightness: 0.9826086489483714
  saturation: 0.26586155872792006
  rhythmicContrast: 0.2219652170315385
purpose: []
